spring:
  application:
    name: Library
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/library_db
    username: username
    password: password
  flyway:
      url: jdbc:postgresql://localhost:5432/library_db
      locations: classpath:db/migration
      user: username
      password: password
      enabled: true
      baseline-on-migrate: true

  logging:
    level:
      org.springframework.web: DEBUG
server:
  port: 8089